# Generated by Django 4.0.3 on 2022-04-27 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100000)),
                ('caption', models.CharField(default='', max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='', max_length=100)),
                ('count', models.CharField(default='1', max_length=100)),
                ('image_url', models.CharField(default='', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ManyToManyField(to='swick.category')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='order2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(default='', max_length=100)),
                ('owner', models.CharField(default='', max_length=10000)),
                ('food', models.CharField(default='', max_length=10000)),
                ('restaurantx', models.CharField(default='', max_length=100)),
                ('time', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(default='1', max_length=100)),
                ('food', models.CharField(default='1', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100000)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('menu', models.ManyToManyField(to='swick.menu')),
            ],
        ),
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('menu', models.ManyToManyField(to='swick.menu')),
                ('name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('orders', models.ManyToManyField(to='swick.order2')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='food',
            field=models.ManyToManyField(to='swick.food'),
        ),
    ]
