# Generated by Django 4.0.3 on 2022-04-27 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swick', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='name',
            new_name='username',
        ),
    ]
