# Generated by Django 4.0.3 on 2022-05-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swick', '0002_rename_name_restaurant_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='order2',
            name='ordertype',
            field=models.CharField(default='', max_length=100),
        ),
    ]
