# Generated by Django 4.0.3 on 2022-05-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swick', '0003_order2_ordertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='order2',
            name='totalprice',
            field=models.CharField(default='', max_length=100),
        ),
    ]
