# Generated by Django 4.0.3 on 2022-04-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swick', '0003_remove_order_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='food',
        ),
        migrations.AddField(
            model_name='order',
            name='food',
            field=models.CharField(default='', max_length=100),
        ),
    ]
