# Generated by Django 4.0.3 on 2022-04-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swick', '0004_remove_order_food_order_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(default='1', max_length=100)),
                ('food', models.ManyToManyField(to='swick.food')),
            ],
        ),
    ]
