# Generated by Django 4.0.3 on 2022-04-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swick', '0005_vcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vcart',
            name='food',
        ),
        migrations.AddField(
            model_name='vcart',
            name='food',
            field=models.CharField(default='1', max_length=10000),
        ),
    ]
